org: renzordiaz
app: mguay-serverless-lambda
service: mguay-serverless-lambda

frameworkVersion: "2 || 3"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  app-api:
    handler: handler.handler
    events:
      - http:
          path: /
          method: GET
          cors: true
      - http:
          path: /{proxy+}
          method: any
          cors: true
